spring:
  application:
    name: auth-service

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: localhost
    port: 1025
    #    USAGE FOR PRODUCTION (e.g., Gmail SMTP):
    #    username: your_email@gmail.com
    #    password: your_app_password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_pass

  flyway:
    url: jdbc:postgresql://localhost:5432/auth_db
    user: auth_user
    password: auth_pass
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
    repair-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

logging:
  level:
    org.springframework.beans.factory: WARN

# CUSTOM CONFIGURATION
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    mfa-token-expiration: 300000        # 5 minutes (5 * 60 * 1000)
    access-token-expiration: 900000     # 15 minutes (15 * 60 * 1000)
    refresh-token-expiration: 604800000 # 7 days (7 * 24 * 60 * 60 * 1000)
  version: v1

  kafka:
    topic:
      auth-events: auth.events
    event:
      version: v1

  rate-limit:
    endpoints:
      login:
        max-requests: 5
        window-seconds: 60
      register:
        max-requests: 3
        window-seconds: 3600
      verify-email:
        max-requests: 5
        window-seconds: 60
      resend-verification:
        max-requests: 3
        window-seconds: 3600
      forgot-password:
        max-requests: 3
        window-seconds: 3600
      reset-password:
        max-requests: 5
        window-seconds: 60
      mfa-validate:
        max-requests: 5
        window-seconds: 60
      refresh:
        max-requests: 10
        window-seconds: 60

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true