services:
  # -----------------------------------------------------------------------
  # APPLICATION SERVICE
  # -----------------------------------------------------------------------
  transfer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfer-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      transfer-postgres:
        condition: service_healthy
    networks:
      - transfer-network
      - shared-network
    restart: on-failure
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8083/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s


  # -----------------------------------------------------------------------
  # POSTGRESQL
  # -----------------------------------------------------------------------
  transfer-postgres:
    image: postgres:16-alpine
    container_name: transfer-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    env_file:
      - .env
    networks:
      - transfer-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    
networks:
  transfer-network:
    name: transfer-network
    driver: bridge
  shared-network:
    external: true