// INITT
@host = http://localhost:8083/api/v1
@correlationId = test-004
#@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0eXBlIjoiYWNjZXNzIiwidXNlckNvZGUiOiJVU1ItREVNTy0xIiwic3ViIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAzIiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiYXVkIjpbImJhbmtpbmctYXBpIl0sImp0aSI6IjdiNmQyNjFmLTQ2OTYtNDNiZS1iMWI4LTNjNWIyOWJjMmJiNyIsImlhdCI6MTc3NTg4MTg1NiwiZXhwIjoxNzc1ODgyNzU2fQ.b7mkAPbYZYiw3Ir3hvUyDKzpPyIRn_INBGb5EZX5joYudBopLMKqvZzSkKet28DuibmpNtpl7QpvDQA2EiDnZhQePRFINfnrQBexcnZBI8v8F6T641gCVSV4jD0NCn67ARQPfqiYQBLWbrwdfKVGq1f9j2fLGyZeoruAtrRjgW7OPSo_KAccWFmD7CzE0Jx3WdPbDBw9uQ3YlZvdsNfECFUeio5AuW_UV1nBB6rZVmSrZk5Dg0LrYfvMQkqL7ByXNAofq23eGoM7a_vmDuYzENEpXU1gQ1t12NUaiMIKl6L9mBBLhlvSgIYHqhyzfcnp9EKIkHp4VZ37MVqAnZ_u9A
@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0eXBlIjoiYWNjZXNzIiwidXNlckNvZGUiOiJVU1ItMjAyNjA0MTctMDAwMDIiLCJzdWIiOiI1ZGY3MmI2OC0yMzIwLTRkYmUtODk4Mi04NjBmYjA0MzEzMGUiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOlsiYmFua2luZy1hcGkiXSwianRpIjoiN2Y2M2Q4NjQtYmFhYy00ZDU3LTg2N2MtZGI4ZGQzYWYxY2I5IiwiaWF0IjoxNzc2NDMzNDQxLCJleHAiOjE3NzY0MzQzNDF9.zvZwHR91PWe9MOCwntgt776T_vEl5l1anO4hxXzIBrGJ8ykZLw5M1ZfT4r1qepCABES2GMpdVdsgG26fgqRaNEHW6DueI6DfDFi7q4eb5x2F8glSwPhfYcm2LPiC-0PJVK68fXVMkd-vQ-fh8opnqCTK71WlNxaxt1eTHuwSlQa8sWqiX6mtuPOgfJ7039jEYtp1OXwC74GEvIEOYHfUVe3FZnQ1N8JvUS2Ogty-AHTyEU1M1_BlpUDGNjNN5DylLD6XLnbZY483oGBjjPQrsTLK1e5QWeZZv1XOHWl5FCoP0ysHWjSmEhrq2HT4aYLOcKXibSK2jLxiGgPspmx2MA

@referenceId =TXN-20260411-d26888ca33
@accountNumber = 4667639409

# di-generate dari sisi Frontend Client
# (Aplikasi Mobile Android/iOS, Website, atau server partner B2B Anda), bukan dari sisi Backend.
@X-Idempotency-Key = 58749674622-20260411-00001B


### Top Up
POST {{host}}/transfers/topup
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
X-Idempotency-Key: {{X-Idempotency-Key}}
Authorization: Bearer {{accessToken}}

{
  "target_account_number": "0280250856",
  "amount": "19980000",
  "currency": "IDR",
  "description": "top up gopay"
}

### Initiate Transfer
POST {{host}}/transfers
Accept: application/json
Content-Type: application/json
X-Idempotency-Key: {{X-Idempotency-Key}}
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "source_account_number": "9240355345",
  "target_account_number": "5874967462",
  "amount": "500000",
  "source_currency": "IDR",
  "target_currency": "IDR",
  "description": "bayar utang"
}

### Confirm Transfer
POST {{host}}/transfers/{{referenceId}}/confirm
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### Cancel Transfer
POST {{host}}/transfers/{{referenceId}}/cancel
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "reason": "salah input nominal"
}

### Get My Transfers
GET {{host}}/transfers
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### Get My Transfers - dengan filter
GET {{host}}/transfers?status=COMPLETED&from=2026-01-01&to=2026-12-31&page=0&size=20
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### Get Transfer Detail
GET {{host}}/transfers/{{referenceId}}
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### Get Account History
GET {{host}}/transfers/accounts/{{accountNumber}}/history
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### Get Account History - dengan filter
GET {{host}}/transfers/accounts/{{accountNumber}}/history?from=2026-01-01&to=2026-12-31&page=0&size=20
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}