@correlationId = test-004
@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJURUxMRVIiXSwidHlwZSI6ImFjY2VzcyIsInVzZXJDb2RlIjoiVEVMTEVSMDAxIiwic3ViIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAyIiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiYXVkIjpbImJhbmtpbmctYXBpIl0sImp0aSI6IjkzODNmZDM0LTBlM2YtNDI2ZS04MGMwLTA3ZjA5NmY0Y2VlOSIsImlhdCI6MTc3NTg4MjA3NSwiZXhwIjoxNzc1ODgyOTc1fQ.h0PZOCMXRVPBAqq8WaBdUG5nLFIgedXg-QuYRxTVqsqff2481xB43LP2hOcv8tXSokiwoLXEE8Il1Z_MvXYh2DgtW3GRYEjw6XGM5Wk4G0-mqQ2d9bF7aFULP77W2HiAT7eX4D_dL_AXhZvvsy8c3eOCavkTwfAH5hmbJ_aIpin57zbVIXxnxGqsEkSH8GTZIQcDo9wSF5kVLVfI7XH7er8ZnJLBgO8paXlH1Tur6Hcmr1OO0VQo5XOHgO_g95Am3_Z6Dak9H0ASudjE2u6zYkYJ-aOOnFXaECw_b3MuBWe5SaVTgCe2f4myOcuc7IWgjTSj6RNBf7itMgvhaPF7Vw


### LOGIN ACC 1
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}

{
  "email": "teller@bank.local",
  "password": "Test@1234"
}


###
#{
#  "email": "maya.kartika.sari@example.com",
#  "password": "Test@1234"
#}



### CREATE DEPOSIT
POST http://localhost:8082/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "CURRENT"
}

### GET ACCOUNT
GET http://localhost:8082/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}