@correlationId = test-004
@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0eXBlIjoiYWNjZXNzIiwidXNlckNvZGUiOiJVU1ItMjAyNjA0MTctMDAwMDIiLCJzdWIiOiI1ZGY3MmI2OC0yMzIwLTRkYmUtODk4Mi04NjBmYjA0MzEzMGUiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOlsiYmFua2luZy1hcGkiXSwianRpIjoiZWQ5NDA1Y2EtYzQ0Mi00ODlhLWIyZWItNWRlMDAwYTk0ZGNkIiwiaWF0IjoxNzc2NDMxNDc5LCJleHAiOjE3NzY0MzIzNzl9.Wqq4Zs8MXVhfK5upXiNLzZnOY7F8ReBVrPZO2OBdCswdBJrQlwSvQ00e7lRt8IOiYLy22rYMFGUgFt5WQn9Ej7438G4-pr3VKIjDqZDyeUA9FZ5zgfDzlV08gaO_WY_wRgYtHs9i29WDa0fXTS0Rp3-Br6rSOupvV4mi40mP7aoaCzgk8JwMXyNN5iRCJVz_IIZ1rmtCaiMjG9HafUA7s-vdPT_hzIHDiZ6luGDtL_DUGu2Du1je0ry1BiqBhz8-VrsIMOL27ird51wMmNQlWrUJmdxydGXu9LYBsepWmYuM1W145hxj-C2ZkAU2S76Q6fn-9IGnPvRRLPvCY7v8gA




### LOGIN ACC 1
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}

{
  "email": "bagas.putra@example.com",
  "password": "StrongPass1!"
}

###
#{
#"email": "teller@bank.local",
#"password": "Test@1234"
#}


### CREATE DEPOSIT
POST http://localhost:8082/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "RDN",
  "rdn_detail": {
    "sid": "IDD123456789011",
    "securities_company": "PT Mandiri Sekuritas"
  }
}


### GET ACCOUNT
GET http://localhost:8082/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}