
#INTIALIZATION
@host = http://localhost:8080
@correlationId = test-004


### 1. EQUEST REGISTER
POST {{host}}/api/v1/auth/register
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}

{
  "full_name": "Maya Kartika Sari",
  "email": "maya.kartika.sari@example.com",
  "password": "ValidPass4$",
  "phone_number": "085612345670",
  "nik": "3275012302940006",
  "address": "Jl. Diponegoro No. 21, Yogyakarta",
  "date_of_birth": "1994-02-23"
}

### 2. VERIFY EMAIL OTP, VISIT http://localhost:8025/ (IN DEV MODE) TO GET OTP CODE
POST {{host}}/api/v1/auth/verify-email
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}

{
  "email": "maya.kartika.sari@example.com",
  "otp_code": "505696"
}

### 4. LOGIN REQUEST
POST {{host}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}

{
  "email": "maya.kartika.sari@example.com",
  "password": "ValidPass4$"
}

### 5. MFA SETUP
# MASUKAN ACCESS TOKEN DARI RESPONSE LOGIN SEBELUMNYA
@accessToken =
POST {{host}}/api/v1/auth/mfa/setup
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

### 6. ENABLE MFA SETUP,
# 1. SCAN QR CODE DARI RESPONSE SEBELUMNYA MENGGUNAKAN APLIKASI AUTHENTICATOR (GOOGLE AUTHENTICATOR, MICROSOFT AUTHENTICATOR, DLL)
# 2. DAPATKAN OTP CODE DARI APLIKASI AUTHENTIC
# 3. KIRIM OTP CODE,
POST {{host}}/api/v1/auth/mfa/setup/verify
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
    "otp_code" : "601325"
}


### 7.  MFA VALIDATE — tukar mfaToken → accessToken + refreshToken
# 1. DAPATKAN MFA TOKEN DARI RESPONSE LOGIN SEBELUMNYA
# 2  OTP COODE DI DAPAT DARI APLIKASI AUTHENTICATOR
@mfaToken = eyJhbGciOiJIUzUxMiJ9.eyJ0eXBlIjoibWZhIiwic3ViIjoiYzEyYzQwOTUtOThlYS00MGQxLThjMmEtZDFiZDI4NmNmMmRmIiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiYXVkIjpbImF1dGgtc2VydmljZSJdLCJqdGkiOiIxZWRkYzU1OC0wNjA4LTRmZDItODExZi1iNGU1MjY3ZjQ0MzkiLCJpYXQiOjE3NzIyOTQwNTgsImV4cCI6MTc3MjI5NDM1OH0.ewlqudUVnexgw9JyApLd4z4HiPdAZlJvk53eQHAhnooPKr6zJEr_vH5opjRvUNgyGgZTGLwFWIcD-CIFTFRnHg
POST {{host}}/api/v1/auth/mfa/validate
Content-Type: application/json
Accept: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{mfaToken}}

{
  "otp_code": "821670"
}