server:
  netty:
    connection-timeout: 10s
    idle-timeout: 60s
  port: 8082

# -----------------------------------------------------------------------
# APPLICATION CONFIGURATION FOR ACCOUNT SERVICE
# -----------------------------------------------------------------------
spring:
  grpc:
    server:
      port: 9091

  application:
    name: account-service
    version: 1.0.0
  jackson:
    property-naming-strategy: SNAKE_CASE

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/account_db
    username: account_user
    password: korie123
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  flyway:
    url: jdbc:postgresql://localhost:5433/account_db
    user: account_user
    password: korie123
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
    listener:
      ack-mode: manual

logging:
  level:
    root: WARN
    com.koriebruh.authservice: INFO
    org.springframework: WARN
    io.r2dbc: WARN
    org.flywaydb: INFO

app:
  kafka:
    topic-produce:
      account-events: account.events
    topic-consume:
      transfer-events: transfer.events
  event:
    version: 1.0.0
  jwt:
    public-key: classpath:keys/public.pem

# -----------------------------------------------------------------------
# CONFIGURATION FOR SPRINGDOC OPENAPI (SWAGGER) DOCUMENTATION
# -----------------------------------------------------------------------
springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# -----------------------------------------------------------------------
# CONFIGURATION FOR ACTUATOR METRICS AND HEALTH CHECKS
# -----------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized

  # Tracing (New Spring 4 Namespace)
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/traces"

  # Metrics (Micrometer OTLP Namespace)
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"

  tracing:
    sampling:
      probability: 1.0

# ---------------------------------------------------
# SERVICE DISCOVERY CONFIGURATION (EUREKA CLIENT)
# ---------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-1:8761/eureka/,http://eureka-2:8762/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 200
    eureka-server-total-connections-per-host: 50
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      version: ${APP_VERSION:1.0.0}
      zone: ${AVAILABILITY_ZONE:default}
      environment: ${SPRING_PROFILES_ACTIVE:development}