// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: account.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountGrpcService_ValidateAccount_FullMethodName  = "/account.AccountGrpcService/ValidateAccount"
	AccountGrpcService_GetAccountDetail_FullMethodName = "/account.AccountGrpcService/GetAccountDetail"
)

// AccountGrpcServiceClient is the client API for AccountGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountGrpcServiceClient interface {
	ValidateAccount(ctx context.Context, in *ValidateAccountRequest, opts ...grpc.CallOption) (*ValidateAccountResponse, error)
	GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailResponse, error)
}

type accountGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountGrpcServiceClient(cc grpc.ClientConnInterface) AccountGrpcServiceClient {
	return &accountGrpcServiceClient{cc}
}

func (c *accountGrpcServiceClient) ValidateAccount(ctx context.Context, in *ValidateAccountRequest, opts ...grpc.CallOption) (*ValidateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAccountResponse)
	err := c.cc.Invoke(ctx, AccountGrpcService_ValidateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountGrpcServiceClient) GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountDetailResponse)
	err := c.cc.Invoke(ctx, AccountGrpcService_GetAccountDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountGrpcServiceServer is the server API for AccountGrpcService service.
// All implementations must embed UnimplementedAccountGrpcServiceServer
// for forward compatibility.
type AccountGrpcServiceServer interface {
	ValidateAccount(context.Context, *ValidateAccountRequest) (*ValidateAccountResponse, error)
	GetAccountDetail(context.Context, *GetAccountDetailRequest) (*AccountDetailResponse, error)
	mustEmbedUnimplementedAccountGrpcServiceServer()
}

// UnimplementedAccountGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountGrpcServiceServer struct{}

func (UnimplementedAccountGrpcServiceServer) ValidateAccount(context.Context, *ValidateAccountRequest) (*ValidateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccount not implemented")
}
func (UnimplementedAccountGrpcServiceServer) GetAccountDetail(context.Context, *GetAccountDetailRequest) (*AccountDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountDetail not implemented")
}
func (UnimplementedAccountGrpcServiceServer) mustEmbedUnimplementedAccountGrpcServiceServer() {}
func (UnimplementedAccountGrpcServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountGrpcServiceServer will
// result in compilation errors.
type UnsafeAccountGrpcServiceServer interface {
	mustEmbedUnimplementedAccountGrpcServiceServer()
}

func RegisterAccountGrpcServiceServer(s grpc.ServiceRegistrar, srv AccountGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountGrpcService_ServiceDesc, srv)
}

func _AccountGrpcService_ValidateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountGrpcServiceServer).ValidateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountGrpcService_ValidateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountGrpcServiceServer).ValidateAccount(ctx, req.(*ValidateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountGrpcService_GetAccountDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountGrpcServiceServer).GetAccountDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountGrpcService_GetAccountDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountGrpcServiceServer).GetAccountDetail(ctx, req.(*GetAccountDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountGrpcService_ServiceDesc is the grpc.ServiceDesc for AccountGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountGrpcService",
	HandlerType: (*AccountGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAccount",
			Handler:    _AccountGrpcService_ValidateAccount_Handler,
		},
		{
			MethodName: "GetAccountDetail",
			Handler:    _AccountGrpcService_GetAccountDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
