# ────────────────────────────────────────────────────────────────────────────────
###  OPENING NEW ACCOUNT FOR USER, [ SAVINGS, CURRENT, GIRO, DEPOSIT RDN ]
# ────────────────────────────────────────────────────────────────────────────────

@host =http://localhost:8082
@correlationId = test-004
@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJDVVNUT01FUiJdLCJ0eXBlIjoiYWNjZXNzIiwidXNlckNvZGUiOiJVU1ItREVNTy0xIiwic3ViIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAzIiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiYXVkIjpbImJhbmtpbmctYXBpIl0sImp0aSI6IjNmNGY0ZjA2LWI5NjMtNDI1OC1hMzIxLWFiN2I2ZDdkNzJjYiIsImlhdCI6MTc3MzU2NTA4OCwiZXhwIjoxNzczNTY1OTg4fQ.UzIg9TUbhGXqXI_4FUL53nKxO5-bjQTCJmPo26CE9L-_UG_WcR2rp53nCuiVXcRZp_NzMdl3FbqQR81zgP7kJk1_oVYnJ9M0ALkx9BRTCb4OLECHH6zqjg-VMfS7xgLybp9EDRBNiavJoEIuKdEVqJJfL7kJDWAzlVaUVu_Mq-FAt2a7mUHGcCiox7dadNbPn52DRIBzprhDBjdWKQFyEM_Z_HE_WZZnZ82j9WxZtw9VQOxvXllMPU-OtZxfW-9cioFxue2nR0eFqYnd3NPJAUrwtvHDMBTm_KSxcJ21ZNavtlQioBE5sGh9RvoSXoZaEhWcqG66MJG9g2N5fghFeA

### NEW SAVINGS
POST {{host}}/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "SAVINGS"
}

### NEW CURRENT AKA GIRO
POST {{host}}/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "CURRENT"
}

### DEPOSIT
POST {{host}}/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "DEPOSIT",
  "deposit_detail": {
    "principal_amount": 500000000,
    "tenor_months": 12,
    "interest_payout": "MONTHLY",
    "auto_rollover": false
  }
}

### RDN
POST {{host}}/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}

{
  "account_type": "RDN",
  "rdn_detail": {
    "sid": "IDD123456789011",
    "securities_company": "PT Mandiri Sekuritas"
  }
}

### LIST MY ACCOUNT ───────────────────────────────────────────────────────────────
GET {{host}}/api/v1/accounts
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}


### GET DETAIL ACCOUNT BY ACCOUNT NUM  ────────────────────────────────────────────
@accountNum = 1187886263

GET {{host}}/api/v1/accounts/{{accountNum}}
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}


### FREEZE ACCOUNT (ADMIN ONLY) BY ACC NUM  ───────────────────────────────────────
#OPTIONS => [ACTIVE, FROZEN, CLOSED]
@accessTokenAdmin = eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJBRE1JTiJdLCJ0eXBlIjoiYWNjZXNzIiwidXNlckNvZGUiOiJBRE1JTjAwMSIsInN1YiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsImlzcyI6ImF1dGgtc2VydmljZSIsImF1ZCI6WyJiYW5raW5nLWFwaSJdLCJqdGkiOiI1Yjk2N2VlNC0wN2ZmLTQwODItOGQ0Yy03MGJlZTdmZmVhMzUiLCJpYXQiOjE3NzM1NjU4NjUsImV4cCI6MTc3MzU2Njc2NX0.vs1nlp6VpNQV1YvXawHY9JW31oEwJCOqQgmfJygeys8wpsa_OflFSEoAifw0_g7ZnSa73WNMA8o09VG_b1yZ1US8K56r7PteQqwiPnMp_GpbDSCrPb-sJ5Mq_uKrNWB8wEDEyIh3cYoB021gBcYZKCip7x3kUNGwmBDxPJtJF14YkkFMRTl91j1KDNP_3oN0sFj_vQQyc6m81TiBA9tTnBY0uh9BWa9VkWNRbbSG_n89BBUSb6XA28YAA-fcWy8-mP82CHHIDaTMcLoKEEx6orzR1NIlI3o3sg_iOgaWeEi--F4-psLZpKjxRqscSUx_T8W-Mk2wYx6CISnvs-XjMA
@accountNumberTarget = 5333905994

PATCH {{host}}/api/v1/accounts/{{accountNumberTarget}}/status
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessTokenAdmin}}

{
    "status": "ACTIVE"
}



### LIST MUTATION TRASACTION  ─────────────────────────────────────────────────────
POST {{host}}/api/v1/accounts/{{accountNum}}/transactions
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}


### DETAIL HISOTRY TRASACTION BY ID ────────────────────────────────────────────────
@id =

POST {{host}}/api/v1/accounts/{{accountNum}}/transactions/{id}
Accept: application/json
Content-Type: application/json
X-Correlation-ID: {{correlationId}}
Authorization: Bearer {{accessToken}}
